spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/perfect_number
    username: postgres
    password: perfect_number_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect